const logger = document.getElementById("logger");
const copy = document.getElementById("copy");
const output = document.getElementById("output");

function getDays(dateStr) {
  const date = new Date(dateStr);
  const diff = Date.now() - date.getTime();
  return Math.floor(diff / (1000 * 60 * 60 * 24));
}

function copyOutputToClipboard() {
  const clipboardItem = new ClipboardItem({
    "text/plain": new Blob([output.textContent], { type: "text/plain" }),
    "text/html": new Blob([output.innerHTML], { type: "text/html" }),
  });
  navigator.clipboard.write([clipboardItem]);
}
copy.addEventListener("click", copyOutputToClipboard);

function formatPRList(name, list) {
  if (list.length === 0) return "";
  return `
<br>
<p><strong>${name}</strong> (${list.length})</p>
<ul>
${
    list.map((pr) =>
      `<li><a href="${pr.url}">${pr.name}</a> · ${pr.daysOpen}d</li>`
    ).join("")
  }
</ul>
  `;
}

async function onSubmit(e) {
  e.preventDefault();
  logger.innerHTML = "";
  copy.style.display = "none";
  output.innerHTML = "";
  const formData = new FormData(e.target, e.submitter);

  const GITHUB_TOKEN = formData.get("token");
  const repos = formData.get("repos").split("\n").filter((r) =>
    r.includes("/")
  );

  const repoQuery = repos.map((r) => "repo:" + r).join(" ");

  // https://docs.github.com/en/graphql/reference/search
  // https://docs.github.com/en/graphql/reference/repos#object-repository
  const query = `
query {
  search(type: REPOSITORY, query: "${repoQuery}", first: 5) {
    nodes {
      ... on Repository {
        pullRequests(first: 100, states:OPEN) {
          edges {
            node {
              files(first:40) {
                edges {
                  node {
                    additions
                    deletions
                  }
                }
              }
              isDraft
              permalink
              publishedAt
              reviewDecision
              reviews(first:5) {
                edges {
                  node {
                    state
                  }
                }
              }
              title
              updatedAt
            }
          }
        }
      }
    }
  }
}
`;

  logger.innerHTML += "<p>Fetching pull requests from Github...</p>";
  const res = await fetch("https://api.github.com/graphql", {
    method: "post",
    headers: { Authorization: `Bearer ${GITHUB_TOKEN}` },
    body: JSON.stringify({ query }),
  });
  const body = await res.json();

  if (!res.ok || body.errors) {
    logger.innerHTML += `<p style="color:red">${
      JSON.stringify(body, null, 2)
    }</p>`;
    return;
  }

  logger.innerHTML += "<p>Formatting response...</p>";
  const pullRequests = [];
  for (const repo of body.data.search.nodes) {
    for ({ node } of repo.pullRequests.edges) {
      if (node.isDraft || node.title.startsWith("[release candidate]")) {
        continue;
      }
      pullRequests.push(node);
    }
  }

  const initialGroups = {
    ready: [],
    partial: [],
    deleting: [],
    small: [],
    remaining: [],
    stale: [],
  };

  const groups = pullRequests.reduce((acc, val) => {
    let group;
    let additions = 0;
    let deletions = 0;

    for (const file of val.files.edges) {
      additions += file.node.additions;
      deletions += file.node.deletions;
    }

    if (getDays(val.updatedAt) > 7 * 3) {
      group = "stale";
    } else if (val.reviewDecision === "APPROVED") {
      group = "ready";
    } else if (
      val.reviews.edges.some((edge) => edge.node.state === "APPROVED")
    ) {
      group = "partial";
    } else if (additions < 120 && deletions < 120) {
      group = "small";
    } else if (deletions - additions > 50) {
      group = "deleting";
    } else {
      group = "remaining";
    }

    acc[group].push({
      name: val.title,
      url: val.permalink,
      daysOpen: getDays(val.publishedAt),
    });
    return acc;
  }, initialGroups);

  const totalNum = Object.values(groups).reduce(
    (acc, val) => acc + val.length,
    0,
  );

  output.innerHTML = `
<p><strong>Pull Request Summary for ${
    repos.map((r) => `<code>${r}</code>`).join(",")
  } (${totalNum} open)</strong></p>
`;

  output.innerHTML += formatPRList("Ready to Merge", groups.ready);
  output.innerHTML += formatPRList("Partially Approved", groups.partial);
  output.innerHTML += formatPRList("Deleting Code", groups.deleting);
  output.innerHTML += formatPRList("Small Changes", groups.small);
  output.innerHTML += formatPRList("Remaining", groups.remaining);
  output.innerHTML += formatPRList("Stale", groups.stale);
  output.innerHTML +=
    `<br><blockquote><em>This summary was <a href="https://github.com/bossley9/pr-summary-generator">generated by a human</a>. Check for mistakes.</em></blockquote>`;

  logger.innerHTML += "<p>Below is an output preview.</p>";

  copy.style.display = "block";
}
document.querySelector("form").addEventListener("submit", onSubmit);
